language: java 
dist: trusty
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "notification-system"
    token:
      secure: "do7Ht2UBoXJ7FqmsyHk3nHFg6rXeQBhDzah/v6ZIXeTtspssOHqUEM/HfJHsFxSJa3YEiiycMikDTquFr4Xb7niI/xkkblZRV4V3wb6CiDMoG471lEFFLw8HKjVf2llmiLycJMBXEwwUj8IDH41Xv0G5A+1YGkPS5GQQeegt4qb5LbpGtj5qO3FYP7m2g1yvRmInm1sqhjpp38CwvRrtEisBnPoEeBK0xXp0cWOwQKZYbQW23mxYkWi+WPZavmEuN4kRnsdNjfm6mREJ1FH4GnerG+jUr9B0Sm+//4PHliWj3eZuQgPdiap3s2JtOR5ocidRvkVEQ5Sj/WUyS3klG5rcCRo2DO6NwFOMYc7SFI6MmrRsTpUxMU7xo+8kRowvTIePJlLnIPr1GZLucRi8RSe+4JMwavpSKJUGTkVIjChRq1NZvouV/ZU2xNsWs5tvAhE9rXrtVkzwDEfrZMVRfzw87nhRdGVduP0lEWjni5GchaLESS1gjRNttYdjSqlS8GQ/ahvTbMOoOqALRe8W9LvO5T1i8azWw0h8tHjlNgyFZozrT2Evr0UM3px5lwzx1BwEvodRgitTAWUJj8xMsg7svYb0vthKc3oLQRBO9niSSTVBzobw0AflfuHj9c6rdNdzawFPO6QYNJgmY6dPYwFktuIdG2TQSmdez/GHYY8="


script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
services:
  - docker

after_success:
   - docker login -u $DOCKER_USER -p $DOCKER_PASS
   - docker build -t $IMAGE_TAG .
   - docker push $IMAGE_TAG
