apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  username: "{{ .Values.properties.username }}"
  server.port: {{ .Values.service.port }}
  kafka.nosy-admin.topic: {{ .Values.properties.kafka_nosy_admin_topic }}
  spring.kafka.producer.bootstrap-servers: {{ .Values.properties.spring_kafka_producer_bootstrap_servers }}
  logging.level.org.springframework.web: DEBUG

  keycloak.enabled: "true"
  keycloak.bearer-only: "true"
  logging.level.org.springframework.security: DEBUG
  keycloak.use-resource-role-mappings: "true"
  keycloak.principal-attribute: preferred_username
  default.nosy.from.address: {{ .Values.properties.default_nosy_from_address }}
  spring.datasource.url: {{ .Values.properties.spring_datasource_url }}
  spring.datasource.username: {{ .Values.properties.spring_datasource_username }}
  spring.datasource.password: {{ .Values.properties.spring_datasource_password }}
  nosy.keycloak.admin.user: {{ .Values.properties.nosy_keycloak_admin_user }}
  nosy.keycloak.admin.password: {{ .Values.properties.nosy_keycloak_admin_password }}
  nosy.client.refreshToken: {{ .Values.properties.nosy_client_refreshToken }}
  keycloak.resource: {{ .Values.properties.keycloak_resource }}
  keycloak.auth-server-url: {{ .Values.properties.keycloak_auth_server_url }}
  keycloak.realm: {{ .Values.properties.keycloak_realm }}
  nosy.client.clientSecret: {{ .Values.properties.nosy_keycloak_admin_password }}
  nosy.client.grantType: password
  nosy.client.keycloak.url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
